"""Public V1-A Genesis requirement-evaluation boundary."""

from .catalog import CATALOG_VERSION, DEFAULT_CATALOG, REAL_RUNTIME_FEATURE_IDS, CatalogFeature, FeatureSupportCatalog
from .evaluator import evaluate, verify_report
from .models import (
    ACCEPTANCE_POLICIES,
    APPROVAL_DECISIONS,
    CATALOG_LAYERS,
    CONSTRAINT_KINDS,
    DISPOSITIONS,
    ERROR_CODES,
    FeatureRequirementReport,
    GenesisRequest,
    GenesisValidationError,
    Requirement,
    RequirementApproval,
    RequirementConstraint,
    RequirementCoverageApproval,
    RequirementProposal,
    RequirementReportItem,
    REPORT_REASON_CODES,
    REPORT_SCHEMA_VERSION,
    REQUIREMENT_KINDS,
    SUPPORT_STATUSES,
)

__all__ = [
    "ACCEPTANCE_POLICIES",
    "APPROVAL_DECISIONS",
    "CATALOG_LAYERS",
    "CATALOG_VERSION",
    "CONSTRAINT_KINDS",
    "DISPOSITIONS",
    "DEFAULT_CATALOG",
    "ERROR_CODES",
    "CatalogFeature",
    "FeatureRequirementReport",
    "FeatureSupportCatalog",
    "GenesisRequest",
    "GenesisValidationError",
    "Requirement",
    "RequirementApproval",
    "RequirementConstraint",
    "RequirementCoverageApproval",
    "RequirementProposal",
    "RequirementReportItem",
    "REPORT_REASON_CODES",
    "REAL_RUNTIME_FEATURE_IDS",
    "REPORT_SCHEMA_VERSION",
    "REQUIREMENT_KINDS",
    "SUPPORT_STATUSES",
    "evaluate",
    "verify_report",
]
