base:
  name: 不断行驶的废土列车
  type: train
  level: 1
  durability: 100
  max_durability: 100
  defense: 10
  space_total: 3
  space_used: 0
  modules: []
  special_properties:
  - 安全基地：不断行驶的废土列车
  cohabitants: []
  defense_log: []
